source 'http://rubygems.org'

gem 'rails', '3.0.5'

gem 'sqlite3'


group :cucumber do
  gem "factory_girl_rails"
  gem "database_cleaner",  ">= 0.4.3"
  gem "cucumber", '0.10.0'
  gem "cucumber-rails", "0.3.2"
  gem 'rspec'
  gem 'rspec-rails'
  gem 'email_spec', '1.1.1'
  gem "johnson", '1.2.0'
  gem "launchy", "0.3.5"
  gem "capybara"
  gem "treetop", "1.4.8"
end
